apiVersion: v1beta1
kind: AgentConfig
metadata:
  name: ocp
rendezvousIP: <MASTER0_IP>
additionalNTPSources:
  - time.google.com
hosts:
  - hostname: master0.ocp.local
    role: master
    rootDeviceHints:
      deviceName: /dev/sda
    interfaces:
      - name: ens192
        macAddress: "<MASTER0_MAC>"
    networkConfig:
      interfaces:
        - name: ens192
          type: ethernet
          state: up
          mac-address: "<MASTER0_MAC>"
          ipv4:
            enabled: true
            dhcp: false
            address:
              - ip: <MASTER0_IP>
                prefix-length: <PREFIX_LENGTH>
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - <DNS_SERVER_IP>
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: <GATEWAY_IP>
            next-hop-interface: ens192
            table-id: 254

  - hostname: master1.ocp.local
    role: master
    rootDeviceHints:
      deviceName: /dev/sda
    interfaces:
      - name: ens192
        macAddress: "<MASTER1_MAC>"
    networkConfig:
      interfaces:
        - name: ens192
          type: ethernet
          state: up
          mac-address: "<MASTER1_MAC>"
          ipv4:
            enabled: true
            dhcp: false
            address:
              - ip: <MASTER1_IP>
                prefix-length: <PREFIX_LENGTH>
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - <DNS_SERVER_IP>
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: <GATEWAY_IP>
            next-hop-interface: ens192
            table-id: 254

  - hostname: master2.ocp.local
    role: master
    rootDeviceHints:
      deviceName: /dev/sda
    interfaces:
      - name: ens192
        macAddress: "<MASTER2_MAC>"
    networkConfig:
      interfaces:
        - name: ens192
          type: ethernet
          state: up
          mac-address: "<MASTER2_MAC>"
          ipv4:
            enabled: true
            dhcp: false
            address:
              - ip: <MASTER2_IP>
                prefix-length: <PREFIX_LENGTH>
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - <DNS_SERVER_IP>
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: <GATEWAY_IP>
            next-hop-interface: ens192
            table-id: 254
