apiVersion: v1
baseDomain: local
metadata:
  name: ocp
compute:
  - architecture: amd64
    name: worker
    replicas: 0
controlPlane:
  architecture: amd64
  name: master
  replicas: 3
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineNetwork:
    - cidr: <MACHINE_NETWORK_CIDR>  # e.g. 10.220.0.0/20
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16
platform:
  baremetal:
    apiVIPs:
      - <API_VIP>
    ingressVIPs:
      - <INGRESS_VIP>
    hosts:
      - name: master0
        role: master
        bootMACAddress: "<MASTER0_MAC>"
      - name: master1
        role: master
        bootMACAddress: "<MASTER1_MAC>"
      - name: master2
        role: master
        bootMACAddress: "<MASTER2_MAC>"
fips: false
pullSecret: '<PULL_SECRET>'
sshKey: '<SSH_PUBLIC_KEY>'
